name: h5py MacOS MWE

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  mwe:
    runs-on: macos-12
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install hdf5

    - name: Pip install step
      shell: bash
      run: |
        pip3 install h5py
